### ISSUE TITLE
[Q&A] Use Python 3 instead Python 2

### ISSUE THREAD

**Issue by dgerod** [daormar/debasher#1]
In the documents you say that this application depends on Python 2, but I recommend you to use Python 3 instead. As this application is new and my expectation is that you and other people will use it during long time, I think that it is better to move now to Python 3 than later. Please, consider that Python 2 will not be maintained after January 1, 2020.

**Comment by daormar** [comment]
Hi dgerod, thanks a lot for the recommendation! of course you are totally right, I will move the code from Python 2 to Python 3 as soon as possible.
